name: never_have_i_ai
description: "Never Have I Ever AI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.5
  uuid: ^4.5.1
  intl: ^0.20.2
  http: ^1.5.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
